apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2
  selector:
   matchLabels:
   app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: alitech/hello
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      restartPolicy: always
         
